#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libssh
Version  : 0.7.5
Release  : 4
URL      : https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz
Source0  : https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libssh-lib
BuildRequires : cmake
BuildRequires : openssl-dev
BuildRequires : zlib-dev

%description
_   _   _                          _
(_) (_) (_)                        (_)
(_)  _  (_) _         _  _   _  _  (_) _
(_) (_) (_)(_) _     (_)(_) (_)(_) (_)(_) _
(_) (_) (_)   (_)  _ (_)  _ (_)    (_)   (_)
(_) (_) (_)(_)(_) (_)(_) (_)(_)    (_)   (_).org

%package dev
Summary: dev components for the libssh package.
Group: Development
Requires: libssh-lib
Provides: libssh-devel

%description dev
dev components for the libssh package.


%package lib
Summary: lib components for the libssh package.
Group: Libraries

%description lib
lib components for the libssh package.


%prep
%setup -q -n libssh-0.7.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513122994
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1513122994
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/cmake/libssh/libssh-config-version.cmake
/usr/lib64/cmake/libssh/libssh-config.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/libssh/callbacks.h
/usr/include/libssh/legacy.h
/usr/include/libssh/libssh.h
/usr/include/libssh/libsshpp.hpp
/usr/include/libssh/server.h
/usr/include/libssh/sftp.h
/usr/include/libssh/ssh2.h
/usr/lib64/libssh.so
/usr/lib64/libssh_threads.so
/usr/lib64/pkgconfig/libssh.pc
/usr/lib64/pkgconfig/libssh_threads.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libssh.so.4
/usr/lib64/libssh.so.4.4.2
/usr/lib64/libssh_threads.so.4
/usr/lib64/libssh_threads.so.4.4.2
